apply plugin: 'com.android.application'
apply from: "https://cdn.mesibo.com/android/mesibo.gradle"

ext {
    PUBLISH_VERSION = "1.0.0"
    PUBLISH_VERSION_CODE = 1
}

android {
    compileSdkVersion project.Mesibo_compileSdkVersion

    defaultConfig {
        applicationId "org.mesibo.messenger"
        minSdkVersion 21
        targetSdkVersion project.Mesibo_targetSdkVersion
        versionCode project.PUBLISH_VERSION_CODE
        versionName project.PUBLISH_VERSION
        buildConfigField "String", "BUILD_VERSION", "\"${project.PUBLISH_VERSION}\""
        buildConfigField "String", "BUILD_TYPE", "\"DEBUG\""
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lintOptions {
        disable 'MissingTranslation'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project.Mesibo_messagingUi
    implementation project.Mesibo_callUi
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
